steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$sid-first-project-428621/hello-world:$SHORT_SHA', '.']
  
  # Step 2: Push the Docker image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$sid-first-project-428621/hello-world:$SHORT_SHA']

images:
  - 'gcr.io/$sid-first-project-428621/hello-world:$SHORT_SHA'
